// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  A_Truss_glb = "A-Truss.glb",
  ABCD_Platform_glb = "ABCD_Platform.glb",
  Answer_A = "Answer_A",
  Answer_B = "Answer_B",
  Answer_C = "Answer_C",
  Answer_D = "Answer_D",
  Arcade_Machines_glb = "Arcade_Machines.glb",
  Arrow_glb = "Arrow.glb",
  Cable_Lights_glb_2 = "Cable_Lights.glb_2",
  Cardboard_Boxes_glb_2 = "Cardboard_Boxes.glb_2",
  Dance_Floor_glb = "Dance_Floor.glb",
  Entrance_Doors_glb = "Entrance_Doors.glb",
  Exterior_Box_glb = "Exterior_Box.glb",
  Exterior_Box_glb_2 = "Exterior_Box.glb_2",
  Gumball_Machines_glb = "Gumball_Machines.glb",
  HUB = "HUB",
  Hanging_Bulbs_glb = "Hanging_Bulbs.glb",
  LeaderBoard_glb = "LeaderBoard.glb",
  LeaderBoard_glb_2 = "LeaderBoard.glb_2",
  Light_A = "Light_A",
  Light_B = "Light_B",
  Light_C = "Light_C",
  Light_D = "Light_D",
  Machine_Cables_glb = "Machine_Cables.glb",
  Main_Building_glb = "Main_Building.glb",
  Main_Building_glb_2 = "Main_Building.glb_2",
  Mesh_Fences_glb = "Mesh_Fences.glb",
  Pillars_glb = "Pillars.glb",
  Platforms_glb = "Platforms.glb",
  Posters_glb = "Posters.glb",
  Prizes_glb = "Prizes.glb",
  Question_Number = "Question_Number",
  Question_Type = "Question_Type",
  Screen_glb = "Screen.glb",
  Screen_Ans_Arrow = "Screen_Ans_Arrow",
  Screen_Text = "Screen_Text",
  Screen_Timer = "Screen_Timer",
  Screen_Timer_Icon = "Screen_Timer_Icon",
  Screen_Vis = "Screen_Vis",
  Servers_glb = "Servers.glb",
  Space = "Space",
  Speakers_glb = "Speakers.glb",
  Stage_glb = "Stage.glb",
  Stage_Light_Blue_glb_1 = "Stage_Light_Blue.glb_1",
  Stage_Light_Blue_glb_2 = "Stage_Light_Blue.glb_2",
  Stage_Light_Blue_glb_3 = "Stage_Light_Blue.glb_3",
  Stage_Light_Blue_glb_4 = "Stage_Light_Blue.glb_4",
  Stage_Light_Blue_glb_5 = "Stage_Light_Blue.glb_5",
  Stage_Light_Blue_glb_6 = "Stage_Light_Blue.glb_6",
  Stools_glb = "Stools.glb",
  Stools_glb_2 = "Stools.glb_2",
  Strip_Lights_glb = "Strip_Lights.glb",
  TRIV_Answers_Text = "TRIV_Answers_Text",
  TRIV_Building_Models = "TRIV_Building_Models",
  TRIV_Triggers = "TRIV_Triggers",
  The_Pixel_Arcade_Sign_glb = "The_Pixel_Arcade_Sign.glb",
  Trigger_Answer_A = "Trigger_Answer_A",
  Trigger_Answer_B = "Trigger_Answer_B",
  Trigger_Answer_C = "Trigger_Answer_C",
  Trigger_Answer_D = "Trigger_Answer_D",
  Trigger_Answer_D_2 = "Trigger_Answer_D_2",
  Trigger_Arcade1 = "Trigger_Arcade1",
  Trigger_Arcade1_Rtrn = "Trigger_Arcade1_Rtrn",
  TriviaBoards_glb = "TriviaBoards.glb",
  TriviaBoards_glb_2 = "TriviaBoards.glb_2",
  TriviaPlayerLocation = "TriviaPlayerLocation",
  Trivia_Sign_glb = "Trivia_Sign.glb",
} 
