// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  A_Truss_glb = "A-Truss.glb",
  ABCD_Platform_glb = "ABCD_Platform.glb",
  Answer_A = "Answer_A",
  Answer_B = "Answer_B",
  Answer_C = "Answer_C",
  Answer_D = "Answer_D",
  Arcade_Machines_V2_glb = "Arcade_Machines_V2.glb",
  Cable_Lights_glb = "Cable_Lights.glb",
  Cable_Lights_glb_2 = "Cable_Lights.glb_2",
  Cardboard_Boxes_glb = "Cardboard_Boxes.glb",
  Dance_Floor_glb = "Dance_Floor.glb",
  Entrance_Doors_glb = "Entrance_Doors.glb",
  Gumball_Machines_glb = "Gumball_Machines.glb",
  HUB = "HUB",
  Hanging_Bulbs_glb = "Hanging_Bulbs.glb",
  Light_A = "Light_A",
  Light_B = "Light_B",
  Light_C = "Light_C",
  Light_D = "Light_D",
  Machine_Cables_glb = "Machine_Cables.glb",
  Main_Building_glb = "Main_Building.glb",
  Main_Building_glb_2 = "Main_Building.glb_2",
  Mesh_Fences_glb = "Mesh_Fences.glb",
  Pillars_glb = "Pillars.glb",
  Platforms_glb = "Platforms.glb",
  Posters_glb = "Posters.glb",
  Prizes_glb = "Prizes.glb",
  Screen_glb = "Screen.glb",
  Screen_Ans_Arrow = "Screen_Ans_Arrow",
  Screen_Text = "Screen_Text",
  Screen_Timer = "Screen_Timer",
  Screen_Timer_Icon = "Screen_Timer_Icon",
  Screen_Vis = "Screen_Vis",
  Servers_glb = "Servers.glb",
  Space = "Space",
  Speakers_glb = "Speakers.glb",
  Stage_glb = "Stage.glb",
  Stage_Light_Blue_glb_1 = "Stage_Light_Blue.glb_1",
  Stage_Light_Blue_glb_2 = "Stage_Light_Blue.glb_2",
  Stage_Light_Blue_glb_3 = "Stage_Light_Blue.glb_3",
  Stools_glb = "Stools.glb",
  Stools_glb_2 = "Stools.glb_2",
  Strip_Lights_glb = "Strip_Lights.glb",
  TRIV_Answers_Text = "TRIV_Answers_Text",
  TRIV_Building_Models = "TRIV_Building_Models",
  TRIV_Triggers = "TRIV_Triggers",
  The_Pixel_Arcade_Sign_glb = "The_Pixel_Arcade_Sign.glb",
  Trigger_Answer_A = "Trigger_Answer_A",
  Trigger_Answer_B = "Trigger_Answer_B",
  Trigger_Answer_C = "Trigger_Answer_C",
  Trigger_Answer_D = "Trigger_Answer_D",
  Trigger_Arcade1 = "Trigger_Arcade1",
  Trigger_Arcade1_Rtrn = "Trigger_Arcade1_Rtrn",
  TriviaPlayerLocation = "TriviaPlayerLocation",
  Trivia_Sign_glb = "Trivia_Sign.glb",
} 
